// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/aria-dashboard/Neural.tsx": () => import("../components/mockups/aria-dashboard/Neural.tsx"),
  "./components/mockups/aria-dashboard/WarRoom.tsx": () => import("../components/mockups/aria-dashboard/WarRoom.tsx")
};
